// Builds the single stylesheet the design-system bundle ships.
//
// The app loads its CSS as two separate imports in `src/main.tsx` — Bootstrap
// first, then `src/index.css` on top of it. The converter takes one file, and
// it copies that file's *contents* rather than following @import, so the two
// are concatenated here in the same order the app loads them. Order is the
// whole point: `focus-*` rules are a thin layer written to win against
// Bootstrap's, and flipping them silently un-styles the library.
//
// Re-run this before every design sync — it is `buildCmd` in
// `.design-sync/config.json`.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const client = dirname(here);

const bootstrap = join(client, "node_modules/bootstrap/dist/css/bootstrap.min.css");
const focus = join(client, "src/index.css");
const out = join(here, "focus-styles.css");

// `@charset` is only legal as the very first bytes of a stylesheet, and a
// sourceMappingURL would point at a file that never ships — both would be
// dead weight in the middle of the concatenation.
const clean = (css) =>
  css
    .replace(/^@charset\s+"[^"]*";\s*/i, "")
    .replace(/\/\*#\s*sourceMappingURL=.*?\*\//g, "")
    .trim();

const bootstrapVersion = JSON.parse(
  readFileSync(join(client, "node_modules/bootstrap/package.json"), "utf8")
).version;

writeFileSync(
  out,
  [
    `/* Focus design system — generated by design-sync/build-css.mjs. Do not edit. */`,
    `/* 1. Bootstrap ${bootstrapVersion} (the LTR build, used in both directions). */`,
    clean(readFileSync(bootstrap, "utf8")),
    `/* 2. src/index.css — the focus-* layer, and the tokens on :root. */`,
    clean(readFileSync(focus, "utf8")),
    "",
  ].join("\n\n")
);

const kb = (readFileSync(out).byteLength / 1024).toFixed(0);
console.log(`design-sync/focus-styles.css written (${kb} KB, bootstrap ${bootstrapVersion} + index.css)`);
